// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Studentmanagement.Entities
{
    public partial class Studentbase
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime StudentDob { get; set; }
        public int Age { get; set; }
        public string FavoriteSubject { get; set; }
        public string InterestedCourse { get; set; }
        public int MathsMark { get; set; }
        public int ChemistryMark { get; set; }
        public int CompMark { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedTimeStamp { get; set; }
        public DateTime UpdatedTimeStamp { get; set; }
        public string Username { get; set; }
        public int Password { get; set; }
    }
}